install:
	ln -sf $(CURDIR)/.gitignore ~/.gitignore
	ln -sf $(CURDIR)/.gitconfig ~/.gitconfig
	ln -sf $(CURDIR)/.emacs ~/.emacs
	ln -sf $(CURDIR)/.zshrc ~/.zshrc
	ln -sf $(CURDIR)/.hgrc ~/.hgrc
	ln -sf $(CURDIR)/.tmux.conf ~/.tmux.conf

	mkdir -p ~/.oh-my-zsh/custom/themes
	ln -sf $(CURDIR)/.oh-my-zsh/custom/themes/victortorres.zsh-theme ~/.oh-my-zsh/custom/themes/victortorres.zsh-theme
